[legends]
_______=___
KC_ALGR(KC_5)=â‚¬
KC_AMPR=&
KC_ASTR=*
KC_AT=@
KC_BSLS=\ |
KC_CIRC=^
KC_COLN=:
KC_COMM=, <
KC_DLR=$
KC_DOT=. >
KC_DQUO="
KC_EQL== +
KC_EXLM=!
KC_GRV=` ~
KC_GT=>
KC_HASH=#
KC_LBRC=[
KC_LCBR={
KC_LPRN=(
KC_LT=<
KC_MINS=- _
KC_PAST=*
KC_PDOT=.
KC_PERC=%
KC_PIPE=|
KC_PLUS=+
KC_PMNS=-
KC_PPLS=+
KC_PSLS=/
KC_QUES=?
KC_QUOT=' "
KC_RBRC=]
KC_RCBR=}
KC_RPRN=)
KC_SCLN=; :
KC_SLSH=/ ?
KC_TILD=~
KC_UNDS=_
MT_LGUI=Super
MT_RGUI=Super
OSM_LSFT=Shift
OSM_RSFT=Shift
